INSERT INTO Customer (First_name, Last_name, Phone_number, Email) VALUES ('Danielle', 'Johnson', '(319) 822-4612', 'jeffreydoyle@hotmail.com');
INSERT INTO Customer (First_name, Last_name, Phone_number, Email) VALUES ('Joy', 'Gardner', '(580) 913-3793', 'johnsonjeffery@hotmail.com');
INSERT INTO Customer (First_name, Last_name, Phone_number, Email) VALUES ('Carolyn', 'Hoffman', '(540) 536-2018', 'shaneramirez@gmail.com');
INSERT INTO Customer (First_name, Last_name, Phone_number, Email) VALUES ('Katherine', 'Moore', '(303) 901-3397', 'joshua35@gmail.com');
INSERT INTO Customer (First_name, Last_name, Phone_number, Email) VALUES ('Christopher', 'Davis', '(914) 324-1741', 'lindsay78@gmail.com');
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('50116', '495 Janet Cape', 'Port Keith', 'Colorado', 1);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('31013', '4752 Kelly Skyway', 'Jacquelineland', 'Rhode Island', 1);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('83728', '327 Nelson Route', 'Lake Mark', 'Wyoming', 2);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('07832', '56413 Lewis Parks', 'Wilkersonmouth', 'Georgia', 2);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('35219', '88496 Cox Dam', 'Daviston', 'Delaware', 3);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('20534', '691 James Mountain', 'Tashatown', 'Utah', 3);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('94967', '845 Kelly Estate', 'Smithview', 'North Carolina', 4);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('23917', '489 Eric Track', 'New Stephanie', 'North Dakota', 4);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('00575', '0154 Brian Wells Apt. 171', 'East Donna', 'Oklahoma', 5);
INSERT INTO Customer_Addresses (Postal_code, Street_address, City, State, Customer_ID) VALUES ('22144', '963 Jennifer Locks Suite 787', 'East Jeffreymouth', 'Alaska', 5);
INSERT INTO Restaurant (Name, Postal_code, Street_address, City, State, Phone_number, Email) VALUES ('Spencer, Chapman and Smith', '93279', '10518 Joshua Oval', 'New David', 'Oregon', '(787) 749-9752', 'esanchez@lee-davis.biz');
INSERT INTO Restaurant (Name, Postal_code, Street_address, City, State, Phone_number, Email) VALUES ('Henderson-Owens', '96062', '106 Mcbride Coves', 'East James', 'New Hampshire', '(816) 796-2212', 'robertramirez@baxter.info');
INSERT INTO Restaurant (Name, Postal_code, Street_address, City, State, Phone_number, Email) VALUES ('Garcia, Pearson and Fernandez', '02435', '26773 Barrera Expressway', 'Smithfurt', 'Kentucky', '(227) 227-4088', 'smitchell@cowan.com');
INSERT INTO Menu_Items (Name, Description, Price, Availability) VALUES ('Customer', 'Design around save article finish.', 20.16, TRUE);
INSERT INTO Menu_Items (Name, Description, Price, Availability) VALUES ('Apply', 'Live try most arm meet surface attention attack.', 19.4, TRUE);
INSERT INTO Menu_Items (Name, Description, Price, Availability) VALUES ('Training', 'Identify walk now often always.', 14.78, TRUE);
INSERT INTO Menu_Items (Name, Description, Price, Availability) VALUES ('Beat', 'Price north first end prove fire.', 14.25, TRUE);
INSERT INTO Menu_Items (Name, Description, Price, Availability) VALUES ('Evidence', 'Capital population lead upon very act.', 29.51, TRUE);
INSERT INTO Menu_Items (Name, Description, Price, Availability) VALUES ('Pretty', 'You available defense enter value thing these.', 5.91, TRUE);
INSERT INTO Restaurant_Menu_Items (Restaurant_ID, MenuItem_ID) VALUES (1, 1);
INSERT INTO Restaurant_Menu_Items (Restaurant_ID, MenuItem_ID) VALUES (1, 2);
INSERT INTO Restaurant_Menu_Items (Restaurant_ID, MenuItem_ID) VALUES (2, 3);
INSERT INTO Restaurant_Menu_Items (Restaurant_ID, MenuItem_ID) VALUES (2, 4);
INSERT INTO Restaurant_Menu_Items (Restaurant_ID, MenuItem_ID) VALUES (3, 5);
INSERT INTO Restaurant_Menu_Items (Restaurant_ID, MenuItem_ID) VALUES (3, 6);
INSERT INTO Delivery_Personnel (First_name, Last_name, Phone_number, Email, Availability) VALUES ('Mike', 'Moore', '(222) 299-4030', 'contrerasangela@hotmail.com', TRUE);
INSERT INTO Delivery_Personnel (First_name, Last_name, Phone_number, Email, Availability) VALUES ('Dale', 'Humphrey', '(935) 226-8851', 'prestonjulia@gmail.com', TRUE);
INSERT INTO Payment_Method (Customer_ID, Method_Type, Masked_Details, Provider_Method_ID, Last_Used) VALUES (1, 'Visa', '**** **** **** 4450', 'pm_35ebd32d-9ad6-40ab-8821-2ddb45b89cd9', CURRENT_TIMESTAMP);
INSERT INTO Payment_Method (Customer_ID, Method_Type, Masked_Details, Provider_Method_ID, Last_Used) VALUES (2, 'Visa', '**** **** **** 2000', 'pm_afffcfd2-341e-440b-97c7-00aab7b56ea7', CURRENT_TIMESTAMP);
INSERT INTO Payment_Method (Customer_ID, Method_Type, Masked_Details, Provider_Method_ID, Last_Used) VALUES (3, 'Visa', '**** **** **** 1373', 'pm_81627cf1-4394-42e6-9a58-7e8aa25d6b29', CURRENT_TIMESTAMP);
INSERT INTO Payment_Method (Customer_ID, Method_Type, Masked_Details, Provider_Method_ID, Last_Used) VALUES (4, 'Visa', '**** **** **** 9916', 'pm_e87d1c78-e7c4-41c7-8049-7b717d106c60', CURRENT_TIMESTAMP);
INSERT INTO Payment_Method (Customer_ID, Method_Type, Masked_Details, Provider_Method_ID, Last_Used) VALUES (5, 'Visa', '**** **** **** 7973', 'pm_a2607723-17a0-4f49-8d01-280fd89a40c0', CURRENT_TIMESTAMP);
INSERT INTO Orders (Created_At, Delivery_time, Real_time_location, Special_Instructions, Status, OrderItem_Price, Taxes, Delivery_Fee, Customer_ID, Restaurant_ID, Personnel_ID, Delivery_Address_ID) VALUES ('2025-05-02 04:02:06.206793', '2025-05-02 04:38:06.206793', '05242 Arnold Meadow Apt. 112, Port Mikeside, NE 17205', 'Final together someone.', 'Processing', 86.87, 5.00, 3.00, 1, 1, 1, 1);
INSERT INTO Orders (Created_At, Delivery_time, Real_time_location, Special_Instructions, Status, OrderItem_Price, Taxes, Delivery_Fee, Customer_ID, Restaurant_ID, Personnel_ID, Delivery_Address_ID) VALUES ('2025-05-19 04:02:06.207140', '2025-05-19 04:46:06.207140', '31586 Sara Freeway Apt. 260, Lake Sandra, MT 88307', 'Environment skin blue the teach.', 'Processing', 25.76, 5.00, 3.00, 2, 2, 2, 2);
INSERT INTO Order_Item (Quantity, MenuItem_ID, Order_ID) VALUES (2, 1, 1);
INSERT INTO Order_Item (Quantity, MenuItem_ID, Order_ID) VALUES (2, 2, 2);
INSERT INTO Payments (Order_ID, PaymentMethod_ID, Transaction_ID, Amount, Payment_Status) VALUES (1, 1, 'txn_eb1fa9f2-d10b-41d0-b317-347038f16a81', 69.25, 'Paid');
INSERT INTO Payments (Order_ID, PaymentMethod_ID, Transaction_ID, Amount, Payment_Status) VALUES (2, 2, 'txn_d20eac17-4e20-4d1a-9983-36e375d66ed4', 35.49, 'Paid');